# -*- coding: utf-8 -*-
"""multiplicacion de matrices.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14nXE1vxtYz9VYz18_6p9cuayo0APJILz
"""

import sympy as sp

# 1. Definir la variable simbólica theta
theta = sp.symbols('theta')

# 2. Definir la matriz de rotación en Z (A1) [cite: 177]
Rz = sp.Matrix([
    [sp.cos(theta), -sp.sin(theta), 0],
    [sp.sin(theta), sp.cos(theta), 0],
    [0, 0, 1]
])

# 3. Definir la matriz de rotación en Y evaluada en 90 grados (A2) [cite: 221]
# Nota: sp.pi/2 representa 90 grados en radianes
Ry90 = sp.Matrix([
    [0, 0, -1],
    [0, 1, 0],
    [1, 0, 0]
])

# 4. Realizar la multiplicación de matrices [cite: 143]
resultado = Rz * Ry90

# 5. Mostrar el resultado de forma elegante
print("Resultado de Rz(theta) * Ry(90):")
sp.pprint(resultado)